# docker-compose.yml
services:
  server:
    build: ./server
    ports:
      - "8081:8081" # Expose server port to host
    # networks:
    #   - app_network
  client:
    build: ./client
    depends_on:
      - server # Ensure server starts before client
    # networks:
    #   - app_network
    # command: ["./client", "server"]
    network_mode: host

# networks:
#   app_network:
#     driver: bridge
