name: My Test Workflow

on:
  push:
    branches: [ "main" ]
  # manual start option
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt install -y build-essential

      - name: Run Test
        run: docker compose up --build